.TH "lxi" "1" "28 March 2016"

.SH "NAME"
lxi \- The LXI control application.

.SH "SYNOPSIS"
.PP
.B lxi
[<options>]

.SH "DESCRIPTION"
.PP
Control LXI devices.

.SH "OPTIONS"

.TP
.B \-v, \--version

Display program version.
.TP
.B \-h, \--help

Display help.

.SH "AUTHOR"
.PP
Written by Martin Lund <martin.lund@keep-it-simple.com>.
