.TH "rigol_1000z_screenshot" "1" "28 March 2016"

.SH "NAME"
rigol_1000z_screenshot \- a tool to capture screenshot from a Rigol 1000z series oscilloscope.

.SH "SYNOPSIS"
.PP
.B rigol_1000z_screenshot
.RB <address>
.RB <filename>

.SH "DESCRIPTION"
.PP
rigol_1000z_screenshot is a commandline application for capturing the PNG
screenshot image from a Rigol 1000z series oscilloscope. For successful capture
the tool requires that the oscilloscope has firmware version
.B 00.04.03.01.05
or later.

.SH "OPTIONS"

.TP
.B <address>
IP address of oscilloscope.

.TP
.B <filename>
Filename that the PNG screenshot image is saved to.


.SH "WEBSITE"
.PP
Visit http://lxi.github.io


.SH "AUTHOR"
.PP
Written by Martin Lund <martin.lund@keep-it-simple.com>.
